<h2>Köszöntés</h2>
<img src="./images/nagyi.jpg">
<h3>Nagyi mama</h3>
<p>Fiát, Andrew-t többször átnevelő táborba küldte, legutolsó alkalommal akkor, amikor az rátámadott George-ra egy anyjával váltott csók után. Nagyi alkoholproblémája akkor vált szorongatóvá, amikor Lynette gyerekeit felügyelve némi bor elfogyasztása után kidőlt, a gyerekek pedig elszöktek. Nagyi nehezen, de rávette magát, hogy elmenjen az Anonim Alkoholisták összejövetelére, ám továbbra is úgy gondolta, hogy nincs problémája az ivással – az összejövetelekre azért ment el, hogy ezzel segítsen megakadályozni fia önállósodását. </p>
<h3>Honnan származik?</h3>
<p>Az általános iskolát Csornán végezte. 1977-ben érettségizett a győri Révai Miklós Gimnáziumban. 1977–78-ban Kalocsán mint előfelvételis teljesített sorkatonai szolgálatot.
<br>
1978-ban felvették az Eötvös Loránd Tudományegyetem Állam- és Jogtudományi Karára, ahol 1983-ban diplomázott. Egyetemi évei alatt a ELTE Jogász Társadalomtudományi Szakkollégium (jelenlegi nevén Bibó István Szakkollégium) tagja volt. Az egyetem elvégzése után a Budapest VI. kerületi Tanács lakáscsere osztályán dolgozott előadóként. 1985-től 1990-ig az MTA Szociológiai Kutatóintézetében dolgozott tudományos munkatársként. Kutatási területe az Országgyűlés törvényalkotó munkája volt. Emellett ügyvédi szakvizsgát tett. </p>
<p>2007-ben bejelentette, hogy indulni kíván a 2009-es európai parlamenti választáson. Miután a választáson mandátumot szerzett, lemondott országgyűlési képviselői mandátumáról; ezt követően az Európai Parlamentben politizált, 2012 tavaszáig. .</p>
<h3>Miért szeretjük?</h3>
<p>Elnöki ciklusa végén derült ki, hogy volt államfőként egy olyan svábhegyi luxusvillába költözik, amit majdnem egy milliárd forint értékben bővítettek ki, ehhez ráadásul egy külön kormányrendeletet is hoztak, hogy a kerület ingatlanépítési szabályait megkerülhessék. Ellenzéki oldalról fel is szólították, hogy ne fogadja el az ingatlant, főleg azután, hogy adóbevallása szerint három ingatlannal is rendelkezik.</p>
<h3>Honnan szerezhető be?</h3>
<p>Nagyi híres szakácsnő lesz, és hihetetlen sikert ér el szakácskönyvével. Férjét, Orsont kiengedték a börtönből, miután Nagyi kérte, hogy vallja be, hogy ő gázolta el Mike Delfinót. Eközben a kis Benjamint Danielle elviszi, mivel egy ügyvéd elvette feleségül, ezentúl tudja ő is nevelni nem várt gyermekét. Ebbe Nagyi teljesen beleroskad, megint inni kezd. Katherine siet a segítségére: hozzáköltözik egy időre, amíg segít barátnőjének letenni az italt. Később együtt dolgoznak Nagyi vállalkozásában mint társak, ám Nagyi Hodge felülkerekedik barátnőjén, aki csak jelentéktelen szereplő a társas vállalkozásban. Orsont sehol sem foglalkoztatják, tekintettel bűnös előéletére. Nagyi ad neki munkát, nem kevesek rosszallására. Andrew megtalálja álmai hercegét, akinek persze megérkezik az édesanyja, aki elcsalná a fiatal párt egy másik városba lakni, ám Nagyi igazi született feleség: házat vásárol nekik a közvetlen közelben, hogy ne veszítse el fiát. </p>
